#!/usr/bin/env python3
"""
Run after `npx cap add android` (the android/ folder is generated in CI and is not committed).

It injects everything native into the generated project:
  * Java sources (plugin, diagnostics, GGUF reader, MainActivity)   -> app/src/main/java/...
  * the C++ engine + CMakeLists                                     -> app/src/main/cpp
  * Gradle: NDK version, CMake hook, arm64-only, Release engine     -> app/build.gradle
  * minSdk 28 (llama.cpp needs a newer libc than Capacitor's default)-> variables.gradle
  * manifest: camera permission + largeHeap
The script fails loudly if any anchor is not found, so a template change in a new
Capacitor version shows up as a clear CI error instead of a silently broken APK.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AND = os.path.join(ROOT, "android")
APP = os.path.join(AND, "app")

ARCH = os.environ.get("CATHEDRAI_ARM_ARCH", "armv8.2-a+dotprod")
TAG = os.environ.get("LLAMA_TAG", "unknown")
NDK = os.environ.get("CATHEDRAI_NDK", "27.2.12479018")
CMAKE = os.environ.get("CATHEDRAI_CMAKE", "3.22.1")
LLAMA = os.path.join(ROOT, "third_party", "llama.cpp")
VERSION = "0.2.0"


def die(msg):
    print("PATCH ERROR: " + msg, file=sys.stderr)
    sys.exit(1)


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


if not os.path.isdir(APP):
    die("android/app not found: run `npx cap add android` first")
if not os.path.isfile(os.path.join(LLAMA, "include", "llama.h")):
    die("llama.cpp not found at " + LLAMA)

# ---------------------------------------------------------------- sources
java_dst = os.path.join(APP, "src", "main", "java", "com", "cathedrai", "app")
os.makedirs(java_dst, exist_ok=True)
jsrc = os.path.join(HERE, "java", "com", "cathedrai", "app")
for fn in os.listdir(jsrc):
    shutil.copy(os.path.join(jsrc, fn), os.path.join(java_dst, fn))

write(os.path.join(java_dst, "BuildInfo.java"), f'''package com.cathedrai.app;

/** Generated by native-android/patch-android.py */
final class BuildInfo {{
    static final String ARM_ARCH = "{ARCH}";
    static final String LLAMA_TAG = "{TAG}";
    static final String APP_VERSION = "{VERSION}";
    private BuildInfo() {{}}
}}
''')

cpp_dst = os.path.join(APP, "src", "main", "cpp")
os.makedirs(cpp_dst, exist_ok=True)
for fn in os.listdir(os.path.join(HERE, "cpp")):
    shutil.copy(os.path.join(HERE, "cpp", fn), os.path.join(cpp_dst, fn))

# ---------------------------------------------------------------- app/build.gradle
gp = os.path.join(APP, "build.gradle")
g = read(gp)
if "cathedrai-native" in g:
    print("build.gradle already patched")
else:
    n_android = len(re.findall(r"^android \{", g, flags=re.M))
    n_default = len(re.findall(r"^\s*defaultConfig \{", g, flags=re.M))
    if n_android != 1 or n_default != 1:
        die(f"unexpected app/build.gradle layout (android blocks={n_android}, defaultConfig blocks={n_default})")

    top = f'''android {{
    // cathedrai-native
    ndkVersion "{NDK}"
    externalNativeBuild {{
        cmake {{
            path "src/main/cpp/CMakeLists.txt"
            version "{CMAKE}"
        }}
    }}
'''
    g = re.sub(r"^android \{\n", lambda m: top, g, count=1, flags=re.M)

    inner = f'''    defaultConfig {{
        ndk {{
            abiFilters "arm64-v8a"
        }}
        externalNativeBuild {{
            cmake {{
                arguments "-DLLAMA_DIR={LLAMA}",
                          "-DCATHEDRAI_ARM_ARCH={ARCH}",
                          "-DCMAKE_BUILD_TYPE=Release",
                          "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
                cppFlags "-std=c++17 -fexceptions"
            }}
        }}
'''
    g = re.sub(r"^\s*defaultConfig \{\n", lambda m: inner, g, count=1, flags=re.M)
    write(gp, g)
    print("patched app/build.gradle")

# ---------------------------------------------------------------- variables.gradle (minSdk)
vp = os.path.join(AND, "variables.gradle")
if os.path.isfile(vp):
    v = read(vp)
    v2, n = re.subn(r"minSdkVersion\s*=\s*\d+", "minSdkVersion = 28", v)
    if n != 1:
        die("could not find minSdkVersion in variables.gradle")
    write(vp, v2)
    print("minSdkVersion -> 28")
else:
    die("android/variables.gradle not found")

# ---------------------------------------------------------------- manifest
mp = os.path.join(APP, "src", "main", "AndroidManifest.xml")
m = read(mp)
if "android.permission.CAMERA" not in m:
    if "<application" not in m:
        die("no <application> tag in AndroidManifest.xml")
    m = m.replace("<application", '<uses-permission android:name="android.permission.CAMERA" />\n    <application', 1)
if "android:largeHeap" not in m:
    m = m.replace("<application", '<application\n        android:largeHeap="true"', 1)
write(mp, m)
print("patched AndroidManifest.xml")

print(f"native patch complete (arch={ARCH}, llama={TAG}, ndk={NDK})")
