#!/usr/bin/env python3
"""
Run after `npx cap add android` (the android/ folder is generated in CI and is not committed).

It injects everything native into the generated project:
  * Java sources (plugin, diagnostics, GGUF reader, MainActivity)   -> app/src/main/java/...
  * the C++ engine + CMakeLists                                     -> app/src/main/cpp
  * launcher icons (native-android/res)                             -> app/src/main/res
  * Gradle: NDK version, CMake hook, arm64-only, Release engine     -> app/build.gradle
  * minSdk 28 (llama.cpp needs a newer libc than Capacitor's default)-> variables.gradle
  * manifest: camera + microphone permissions, <queries> for TTS/speech services, largeHeap
The script fails loudly if any anchor is not found, so a template change in a new
Capacitor version shows up as a clear CI error instead of a silently broken APK.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AND = os.path.join(ROOT, "android")
APP = os.path.join(AND, "app")

ARCH = os.environ.get("CATHEDRAI_ARM_ARCH", "armv8.2-a+dotprod")
TAG = os.environ.get("LLAMA_TAG", "unknown")
NDK = os.environ.get("CATHEDRAI_NDK", "27.2.12479018")
CMAKE = os.environ.get("CATHEDRAI_CMAKE", "3.22.1")
LLAMA = os.path.join(ROOT, "third_party", "llama.cpp")
VERSION = "0.5.0"


def die(msg):
    print("PATCH ERROR: " + msg, file=sys.stderr)
    sys.exit(1)


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


if not os.path.isdir(APP):
    die("android/app not found: run `npx cap add android` first")
if not os.path.isfile(os.path.join(LLAMA, "include", "llama.h")):
    die("llama.cpp not found at " + LLAMA)

# ---------------------------------------------------------------- sources
java_dst = os.path.join(APP, "src", "main", "java", "com", "cathedrai", "app")
os.makedirs(java_dst, exist_ok=True)
jsrc = os.path.join(HERE, "java", "com", "cathedrai", "app")
for fn in os.listdir(jsrc):
    shutil.copy(os.path.join(jsrc, fn), os.path.join(java_dst, fn))

write(os.path.join(java_dst, "BuildInfo.java"), f'''package com.cathedrai.app;

/** Generated by native-android/patch-android.py */
final class BuildInfo {{
    static final String ARM_ARCH = "{ARCH}";
    static final String LLAMA_TAG = "{TAG}";
    static final String APP_VERSION = "{VERSION}";
    private BuildInfo() {{}}
}}
''')

cpp_dst = os.path.join(APP, "src", "main", "cpp")
os.makedirs(cpp_dst, exist_ok=True)
for fn in os.listdir(os.path.join(HERE, "cpp")):
    shutil.copy(os.path.join(HERE, "cpp", fn), os.path.join(cpp_dst, fn))

# ---------------------------------------------------------------- launcher icon
# Capacitor's template ships an adaptive icon (mipmap-anydpi-v26) that wins over plain PNGs on Android 8+,
# so it is removed and the app's own PNG icons are copied in.
res_src = os.path.join(HERE, "res")
res_dst = os.path.join(APP, "src", "main", "res")
if os.path.isdir(res_src):
    for d in ("mipmap-anydpi-v26", "mipmap-anydpi"):
        shutil.rmtree(os.path.join(res_dst, d), ignore_errors=True)
    for d in os.listdir(res_src):
        os.makedirs(os.path.join(res_dst, d), exist_ok=True)
        for fn in os.listdir(os.path.join(res_src, d)):
            shutil.copy(os.path.join(res_src, d, fn), os.path.join(res_dst, d, fn))
    print("launcher icons installed")

# ---------------------------------------------------------------- app/build.gradle
gp = os.path.join(APP, "build.gradle")
g = read(gp)
if "cathedrai-native" in g:
    print("build.gradle already patched")
else:
    n_android = len(re.findall(r"^android \{", g, flags=re.M))
    n_default = len(re.findall(r"^\s*defaultConfig \{", g, flags=re.M))
    if n_android != 1 or n_default != 1:
        die(f"unexpected app/build.gradle layout (android blocks={n_android}, defaultConfig blocks={n_default})")

    top = f'''android {{
    // cathedrai-native
    ndkVersion "{NDK}"
    externalNativeBuild {{
        cmake {{
            path "src/main/cpp/CMakeLists.txt"
            version "{CMAKE}"
        }}
    }}
'''
    g = re.sub(r"^android \{\n", lambda m: top, g, count=1, flags=re.M)

    inner = f'''    defaultConfig {{
        ndk {{
            abiFilters "arm64-v8a"
        }}
        externalNativeBuild {{
            cmake {{
                arguments "-DLLAMA_DIR={LLAMA}",
                          "-DCATHEDRAI_ARM_ARCH={ARCH}",
                          "-DCMAKE_BUILD_TYPE=Release",
                          "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
                cppFlags "-std=c++17 -fexceptions"
            }}
        }}
'''
    g = re.sub(r"^\s*defaultConfig \{\n", lambda m: inner, g, count=1, flags=re.M)
    write(gp, g)
    print("patched app/build.gradle")

# ---------------------------------------------------------------- variables.gradle (minSdk)
vp = os.path.join(AND, "variables.gradle")
if os.path.isfile(vp):
    v = read(vp)
    v2, n = re.subn(r"minSdkVersion\s*=\s*\d+", "minSdkVersion = 28", v)
    if n != 1:
        die("could not find minSdkVersion in variables.gradle")
    write(vp, v2)
    print("minSdkVersion -> 28")
else:
    die("android/variables.gradle not found")

# ---------------------------------------------------------------- manifest
mp = os.path.join(APP, "src", "main", "AndroidManifest.xml")
m = read(mp)
if "android.permission.CAMERA" not in m:
    if "<application" not in m:
        die("no <application> tag in AndroidManifest.xml")
    m = m.replace("<application", '<uses-permission android:name="android.permission.CAMERA" />\n    <application', 1)
if "android:largeHeap" not in m:
    m = m.replace("<application", '<application\n        android:largeHeap="true"', 1)
if "<application" not in m:
    die("no <application> tag in AndroidManifest.xml")


def add_before_application(block):
    """Insert a top-level manifest element just before <application (never inside it)."""
    global m
    m = m.replace("<application", block + "\n    <application", 1)


for perm in ("android.permission.RECORD_AUDIO", "android.permission.MODIFY_AUDIO_SETTINGS"):
    if perm not in m:
        add_before_application(f'<uses-permission android:name="{perm}" />')
if "android.hardware.microphone" not in m:
    add_before_application('<uses-feature android:name="android.hardware.microphone" android:required="false" />')

# <queries>: Android 11+ package visibility for text-to-speech and speech recognition services
q_items = {
    "android.intent.action.TTS_SERVICE": '<intent><action android:name="android.intent.action.TTS_SERVICE" /></intent>',
    "android.speech.RecognitionService": '<intent><action android:name="android.speech.RecognitionService" /></intent>',
}
missing = [v for k, v in q_items.items() if k not in m]
if missing:
    body = "\n        ".join(missing)
    if re.search(r"<queries\s*>", m):
        m = re.sub(r"(<queries\s*>)", lambda mo: mo.group(1) + "\n        " + body, m, count=1)
    elif re.search(r"<queries\s*/>", m):
        m = re.sub(r"<queries\s*/>", lambda mo: "<queries>\n        " + body + "\n    </queries>", m, count=1)
    else:
        add_before_application("<queries>\n        " + body + "\n    </queries>")
write(mp, m)
print("patched AndroidManifest.xml")

print(f"native patch complete (arch={ARCH}, llama={TAG}, ndk={NDK})")
